version: '3.7'

services:
  backend:
    build: src
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8080
    volumes:
      - ./src/:/app/
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=postgresql://dummy_pg_user:dummy_pg_pwd@db/dummy_pg_db
      - SUPERUSER_LOGIN=dummy_login
      - SUPERUSER_PWD=dummy_pwd
      - CORS_ORIGIN=${CORS_ORIGIN}
      - BUCKET_NAME=${BUCKET_NAME}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_REGION=${S3_REGION}
      - S3_ENDPOINT_URL=${S3_ENDPOINT_URL}
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=dummy_pg_user
      - POSTGRES_PASSWORD=dummy_pg_pwd
      - POSTGRES_DB=dummy_pg_db
  nginx:
    build: nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend

volumes:
  postgres_data:
