"""init

Revision ID: f84a0ed81bdc
Revises:
Create Date: 2024-05-30 12:00:11.710286

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f84a0ed81bdc"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "annotations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("gif_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("label", sa.Enum("WILDFIRE", "NOTHING", "UNSURE", name="label"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("camera_id", sa.Integer(), nullable=True),
        sa.Column("origin", sa.Enum("PYRONEARFRENCHAPI", "ALERTWILDFIRE", name="origin"), nullable=True),
        sa.Column("origin_url", sa.String(), nullable=True),
        sa.Column("angle_of_view", sa.Float(), nullable=True),
        sa.Column("elevation", sa.Float(), nullable=True),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lon", sa.Float(), nullable=True),
        sa.Column("is_trustable", sa.Boolean(), nullable=True),
        sa.Column("last_active_at", sa.DateTime(), nullable=True),
        sa.Column("last_image", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer()),
        sa.Column("role", sa.Enum("ADMIN", "AGENT", "USER", name="userrole"), nullable=False),
        sa.Column("login", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_login"), "user", ["login"], unique=True)
    op.create_table(
        "detections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("annotation_id", sa.Integer(), nullable=True),
        sa.Column("azimuth", sa.Float(), nullable=False),
        sa.Column("bucket_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("bboxes", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("bbox_verified", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("prediction", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["annotation_id"],
            ["annotations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("detection")
    op.drop_index(op.f("ix_user_login"), table_name="user")
    op.drop_table("user")
    op.drop_table("source")
    op.drop_table("annotation")
    # ### end Alembic commands ###
